// user types

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_ACCOUNT_REQUEST = 'USER_ACCOUNT_REQUEST'
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS'
export const USER_ACCOUNT_FAIL = 'USER_ACCOUNT_FAIL'
    